version: "3.9"

services:
  # database section
  postgredb:
    container_name: postgredb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgredb_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pdadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=longvn@epayjsc.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    
  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  