version: "3.9"

services:
  # database section
  postgredb:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4
    
  redis:
    image: redis:alpine
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.0.1
  
#  kafka:
#    image: confluentinc/cp-kafka:7.0.1
  
#  kafka-ui:
#    image: provectuslabs/kafka-ui
  
#network section
networks:
  defaults:
    name: epay_networks
    driver: bridge
    
#volumes section    
volumes:
  postgredb_data: 
    name: postgredb_data
  pgadmin_data:
    name: pgadmin_data
